apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-c-config-production
  namespace: exam-3
data:
  config.json: |
    {
      "app_name": "portal-c",
      "subtitle": "Production - GitOps via Argo CD",
      "owner": "Hans"
    }
